eval_unrolls: 500
eval_every_x_epochs: 10
save_every_x_epochs: 1
test_every_x_epochs: 10
write_csv_every_x_batches: 1
N_train: 1000
N_test: 1000
num_samples_test: 1000
num_samples_train: 1000

plot_iterates: [0, 10, 20]
accuracies: [1, .1, .03, .01, .001, .0001]
iterates_visualize: [15]

vis_num: 25
supervised: False
train_unrolls: 15
skip_startup: False


pac_bayes_num_samples: 5
pac_bayes_flag: False

pac_bayes_cfg:
  init_var: 1e-3
  c: 10.0
  b: 100
  delta: 0.0001
  rep: True
  penalty_coeff: 1.0
  deterministic: False
  target_pen: 0.3
  frac_solved_accs: fp_full

custom_loss: True
