N_train: 100 # the number of base problems
N_test: 10 # the number of samples

data:
  datetime: ''

eval_batch_size_test: 50
eval_unrolls: 200 #20000

classical_nearest_neighbor: True
classical: True

pac_bayes_cfg:
  delta: 0.0001
  rep: True
  frac_solved_accs: fp_full

# used for logging and plotting (not very important)
plot_iterates: [0, 10, 20]
accuracies: [.1, .01, .001, .0001]